;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        c-electric-lt-gt
        c-electric-semi&comma
        c-indent-line-or-region
        indent-for-tab-command
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-colon
        ))
