;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        c-electric-star
        electric-pair-delete-pair
        python-indent-dedent-line
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        ))
