;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        c-electric-brace
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        indent-for-tab-command
        overwrite-mode
        previous-buffer
        upcase-region
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-colon
        helm-confirm-and-exit-minibuffer
        ))
